layout_spectrum: 0.3647849846962323
typography_spectrum: 0.5742415373488375
color:
  lightness: 0.619430091221826
  brandColors:
    - '#41286E'
    - '#C9C9C8'
    - '#00FF00'
    - '#FFFF00'
    - '#FF00FF'
  saturation: 0.630501977876843
  brandStrength: 0.037564748210906246
  rhythmicContrast: 0.09243689625358006
name: Melbourne Building Management
analytics: {}
github: true
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
content_rating:
  adult: false
opengraph: {}
title: Melbourne Building Management
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dd3752cb-a688-4e76-9c00-1ff184935279.png
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d20144a-b256-4e15-b669-6efd2858db12.png
